baseURL = "https://maxsharabayko.github.io/blog/"
languageCode = "en-us"
title = "Max Sharabayko Blog"
theme = "mainroad"
paginate = "10"

[Author]
  name = "Maxim Sharabayko"
  bio = "To be added."
  avatar = "img/avatar.png"

[Params]
  #subtitle = "A personal blog about everything"
  description = "A personal blog about everything"
  copyright = "Maxim Sharabayko"
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" 
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML"
  
[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  #single = false # Configure layout for single pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
  
[Params.widgets.social]
  # Enable parts of social widget
  #facebook = "username"
  #instagram = "username"
  linkedin = "maxim-sharabayko"
  #telegram = "username"
  github = "maxsharabayko"
  #gitlab = "username"
  #bitbucket = "username"
  #email = "example@example.com"
  
[menu]

  [[menu.main]]
    identifier = "blog"
    name = "blog"
    pre = "<i class='fa fa-heart'></i>"
    url = "/"
    weight = -110

#  [[menu.main]]
#    name = "papers"
#    url = "/papers/"
#    weight = -100
