name: Publish with Hugo

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Patch Theme
        run:
          cd themes/mainroad
          git apply ../../theme.patch
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true
      - name: Build
        run: hugo --minify
      - name: Publish Site
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
